In [1]:
import torch

## 张量连结

In [5]:
x = torch.arange(12, dtype=torch.float32).reshape((3, 4))
y = torch.tensor([[2.0, 1, 4, 3], [2.0, 1, 4, 3], [2.0, 1, 4, 3]])
# 竖向连结(行)        # 横向连结(列)
torch.cat((x, y), dim=0), torch.cat((x,y), dim=1)
# 三维 dim = 2等等

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 2.,  1.,  4.,  3.],
         [ 2.,  1.,  4.,  3.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  2.,  1.,  4.,  3.],
         [ 8.,  9., 10., 11.,  2.,  1.,  4.,  3.]]))

## 元素求和

In [6]:
x.sum()

tensor(66.)

## 广播机制
* 自动进行或者列上的扩展，满足两个张量计算

In [7]:
a = torch.arange(3).reshape((3,1))
b = torch.arange(2).reshape((1,2))
a, b


(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [8]:
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

## 元素访问

In [9]:
x

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [10]:
x[1, 2]

tensor(6.)

In [11]:
x[0:2 ,:]

tensor([[0., 1., 2., 3.],
        [4., 5., 6., 7.]])

In [12]:
x[-1, 2]

tensor(10.)

In [13]:
x[:-1,1]

tensor([1., 5.])

## 运行一些操作可能导致为新结果分配内存

In [14]:
before = id(y)
y = y + x
id(y) == before
# y 不会等于之前的 y,因为在y重新赋值的时候,之前的y已经被析构了

False

## 原地操作

In [16]:
z = torch.zeros_like(y)
print("id:z", id(z))
z[:] = x + y
print("id:z", id(z))

id:z 1748852111808
id:z 1748852111808


## 如果后续计算中没有重复使用x, 也可以使用x[:] = x+y或者 x+=y来减少操作的内存开销

In [17]:
before = id(x)
x += y
id(x) == before

True

## 转化为numpy

In [18]:
A = x.numpy()
B = torch.tensor(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

## 将大小为1的张量转换为Python张量

In [19]:
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)